trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python sales_data_pipeline.py
    displayName: 'Run Data Processing Pipeline'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'raw_sales_data.csv'
      ArtifactName: 'RawSalesData'
      publishLocation: 'Container'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'processed_sales_data.csv'
      ArtifactName: 'ProcessedSalesData'
      publishLocation: 'Container'
